controller_manager: # Node name
  ros__parameters:
    update_rate: 30 # Has to be an integer otherwise errors are encountered

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_broadcaster:
  ros__parameters:

    sensor_name: "mpu6050"
    frame_id: "imu_link"

    # Covariance from 500 data points
    static_covariance_orientation: [3.26861e-06, 0.0, 0.0, 0.0, 1.03192e-05, 0.0, 0.0, 0.0, 1.13972e-05]
    static_covariance_angular_velocity: [2.53901e-07, 0.0, 0.0, 0.0, 5.54777e-07, 0.0, 0.0, 0.0, 3.71681e-07]
    static_covariance_linear_acceleration: [0.00157523, 0.0, 0.0, 0.0, 0.000837686, 0.0, 0.0, 0.0, 0.00110392]
